name: Crates

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_PREFIX: ${{ github.event.repository.name }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ created ]
  repository_dispatch:
    types: [ publish ]
  workflow_dispatch:

jobs:
  publish:
    env:
      CARGO_PACKAGE_NAME: ${{ github.event.repository.name }}
    name: Publish (${{ github.event.repository.name }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ env.CARGO_PACKAGE_NAME }})
        run: cargo publish --all-features -v -p ${{ env.CARGO_PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}